#! python3.
import openpyxl
import os
import pandas as pd
import tkinter as tk


screen = tk.Tk()
screen.geometry("550x400")
screen.title("Expenses")

filename = 'C:/Users/dummy/OneDrive/Desktop/1/Programming/Programming/expenses tracker/Expenses.xlsx'

#Path to open the excel file
def file_path():
    os.startfile(filename)
    exit()

#This class is used for calculating and inserting totals into entry boxes
class totals:
    def __init__(self):
        #Root stuff
        self.wb = openpyxl.load_workbook(filename)
        self.sheets = self.wb.sheetnames
        self.df = pd.read_excel(filename, self.sheets[-1])
        self.ws = self.wb[self.sheets[-1]]
        self.page = self.wb.active
        #Totals
        self.bill_tot = round(self.df['Bills'].sum(), 2)
        self.total = round(self.df['Price'].sum(), 2)
        self.tot_gas = round(self.df.query('GAS==1')['Price'].sum(), 2)
        self.tot_food = round(self.df.query('FOOD==1')['Price'].sum(), 2)
        self.tot_clothes = round(self.df.query('CLOTHES==1')['Price'].sum(), 2)
        self.tot_supplies = round(self.df.query('SUPPLIES==1')['Price'].sum(), 2)
        self.tot_games = round(self.df.query('LUXURY==1')['Price'].sum(), 2)
        self.tot_credit = round(self.df.query('CREDIT==1')['Price'].sum(), 2)   
#This total is how much moeny overall was spent and bills were payed
    def main_total(self):
        var.entry6a.set(str(self.bill_tot) + '$')
        var.entry7.set(str(self.total - self.tot_credit) + '$')
#This one is to show the total amount amount of money spent in different categories of items
    def cats_total(self):
        var.second1.set(str(self.tot_gas) + '$')
        var.second2.set(str(self.tot_food) + '$')
        var.second3.set(str(self.tot_clothes) + '$')
        var.second4.set(str(self.tot_supplies) + '$')
        var.second5.set(str(self.tot_games) + '$')
        var.second6.set(str(self.tot_credit) + '$')
    

t = totals()

#I had alot of variables because of all the entry boxes and checkbuttons in the app, so I decided to stick them in a class so I could
#easily use them
class variables:
    def __init__(self):
        self.second1 = tk.DoubleVar(screen)
        self.second2 = tk.DoubleVar(screen)
        self.second3 = tk.DoubleVar(screen)
        self.second4 = tk.DoubleVar(screen)
        self.second5 = tk.DoubleVar(screen)
        self.second6 = tk.DoubleVar(screen)
        self.entry1 = tk.StringVar(screen)
        self.entry2 = tk.StringVar(screen)
        self.entry3 = tk.DoubleVar(screen)
        self.entry4 = tk.StringVar(screen)
        self.entry5 = tk.StringVar(screen)
        self.entry6 = tk.DoubleVar(screen)
        self.entry6a = tk.StringVar(screen)
        self.entry7 = tk.StringVar(screen)
        self.check1 = tk.DoubleVar(screen)
        self.check2 = tk.DoubleVar(screen)
        self.check3 = tk.DoubleVar(screen)
        self.check4 = tk.DoubleVar(screen)
        self.check5 = tk.DoubleVar(screen)
        self.check6 = tk.DoubleVar(screen)


var = variables()

#This function is the window that shows me how much i have spent in each categorie of items (gas, clothes, food, tec.)
def second_window():
    window = tk.Toplevel(screen)
    window.geometry('500x400')
    window.title('Categories')
    L = tk.Label(window, text='Categories', font=('arial', 30, 'bold')).pack(side='top')
    L1 = tk.Label(window, text='GAS:', font=('arial', 15)).place(x=84, y=80)
    L2 = tk.Label(window, text='FOOD:', font=('arial', 15)).place(x=67, y=130)
    L3 = tk.Label(window, text='CLOTHES:', font=('arial', 15)).place(x=33, y=180)
    L4 = tk.Label(window, text='SUPPLIES:', font=('arial', 15)).place(x=30, y=230)
    L5 = tk.Label(window, text='LUXURY:', font=('arial', 15)).place(x=52, y=280)
    L6 = tk.Label(window, text='CREDIT:', font=('arial', 15)).place(x=52, y=330)
    E1 = tk.Entry(window, textvar=var.second1, bd=5)
    E1.place(x=150, y=80)
    E2 = tk.Entry(window, textvar=var.second2, bd=5)
    E2.place(x=150, y=130)
    E3 = tk.Entry(window, textvar=var.second3, bd=5)
    E3.place(x=150, y=180)
    E4 = tk.Entry(window, textvar=var.second4, bd=5)
    E4.place(x=150, y=230)
    E5 = tk.Entry(window, textvar=var.second5, bd=5)
    E5.place(x=150, y=280)
    E6 = tk.Entry(window, textvar=var.second6, bd=5)
    E6.place(x=150, y=330)
    B1 = tk.Button(window, text='Show_Totals', font=('arial', 15, 'bold'), command=t.cats_total).place(x=320, y=100)
    window.mainloop

#This class is for creating a new sheet when the current month has ended. It creates a new sheet that I can personnaly name threw the 
#sheet_window function, then it saves the total of money spent and total money spent in each categorie in the current sheet. So if I need
#to go back I see exactly what I spent on, and see what I should cut down on. Its my favorite class in this.
class NEW_SHEET:
    def __init__(self):
        self.wb = openpyxl.load_workbook(filename)
        self.sheets = self.wb.sheetnames
        self.prof_name = tk.StringVar(screen)
        self.page = self.wb.active

    def sheet_window(self):
        window = tk.Toplevel(screen)
        l1 = tk.Label(window, text='NEW_SHEET')
        l1.pack(side='top')
        e1 = tk.Entry(window, textvar=self.prof_name, bd=5)
        e1.pack(side='left')
        b1 = tk.Button(window, text='ENTER', command=self.save_total)
        b1.pack(side='right')

    def save_total(self):
        ws = self.wb[self.sheets[-1]]
        grand_tot = ((t.total - t.tot_credit) + t.bill_tot)
        ws['M2'] = grand_tot
        ws['M3'] = 'GAS: ' + str(t.tot_gas)
        ws['M4'] = 'FOOD: ' + str(t.tot_food)
        ws['M5'] = 'CLOTHES: ' + str(t.tot_clothes)
        ws['M6'] = 'SUPPLIES: ' + str(t.tot_supplies)
        ws['M7'] = 'LUXURY: ' + str(t.tot_games)
        ws['M8'] = 'CREDIT: ' + str(t.tot_credit)
        self.wb.save(filename)
        self.new_sheet()

    def new_sheet(self):
        self.wb.create_sheet(self.prof_name.get())
        self.append_to()
        self.wb.save(filename)

    def append_to(self):
        cats = ['Store', 'Item', 'Price', 'Payment_Method', 'Date_Purchased', 'Bills', 
        'GAS', 'FOOD','CLOTHES', 'SUPPLIES', 'LUXURY', 'CREDIT', 'TOTAL']
        sheets = self.wb.sheetnames
        ws = self.wb[sheets[-1]]
        ws.append(cats)


exc = NEW_SHEET()

#This is the main window where you insert what you spent money on, and how much you have spent.
class Main_Window:
    def __init__(self, master):
        self.master = master
        self.L1 = tk.Label(master, text='eTracker', font=('arial', 40, 'bold')).pack(side='top')
        self.L2 = tk.Label(master, text='Store:', font=('arial', 15)).place(x=140, y=85)
        self.L3 = tk.Label(master, text='Item:', font=('arial', 15)).place(x=149, y=135)
        self.L4 = tk.Label(master, text='Price:', font=('arial', 15)).place(x=143, y=185)
        self.L5 = tk.Label(master, text='Payment_Method:', font=('arial', 15)).place(x=34, y=235)
        self.L6 = tk.Label(master, text='Date_Purchased:', font=('arial', 15)).place(x=42, y=285)
        self.L7 = tk.Label(master, text="Bills:", font=('arial', 15)).place(x=439, y=230)
        self.L8 = tk.Label(master, text="Bills_Payed:", font=('arial', 15)).place(x=390, y=338)
        self.L9 = tk.Label(master, text='Total', font=('arial', 25)).place(x=157, y=327)
        self.E1 = tk.Entry(master, textvar=var.entry1, bd=5)
        self.E1.place(x=210, y=86)
        self.E2 = tk.Entry(master, textvar=var.entry2, bd=5)
        self.E2.place(x=210, y=136)
        self.E3 = tk.Entry(master, textvar=var.entry3, bd=5)
        self.E3.place(x=210, y=186)
        self.E4 = tk.Entry(master, textvar=var.entry4, bd=5)
        self.E4.place(x=210, y=236)
        self.E5 = tk.Entry(master, textvar=var.entry5, bd=5)
        self.E5.place(x=210, y=286)
        self.E6 = tk.Entry(master, textvar=var.entry6, bd=5)
        self.E6.place(x=400, y=260)
        self.E6a = tk.Entry(master, textvar=var.entry6a, bd=5, font=('arial', 13))
        self.E6a.place(x=350, y=369)
        self.E7 = tk.Entry(master, textvar=var.entry7, bd=5, font=('arial', 15))
        self.E7.place(x=80, y=365)
        self.M1 = tk.Menu(master)
        self.profM1 = tk.Menu(self.M1, tearoff=0)
        self.profM1.add_command(label='NEW', command=exc.sheet_window)
        self.profM1.add_command(label='VIEW', command=file_path)
        self.profM1.add_command(label='CATEGORIES', command=second_window)
        self.M1.add_cascade(label='EDIT', menu=self.profM1)
        master.bind('<Return>', self.clear)

    def clear(self, _event=None):
        info.enter()
        self.E1.delete(0, 'end')
        self.E2.delete(0, 'end')
        self.E3.delete(0, 'end')
        self.E3.insert(0, 0)
        self.E4.delete(0, 'end')
        self.E5.delete(0, 'end')
        self.E6.delete(0, 'end')
        self.E6.insert(0, 0)
        self.E6a.delete(0, 'end')
        self.E7.delete(0, 'end')


m = Main_Window(screen)


# This final class enters all the information into the excel file. The checkbuttons are used for adding whatever item im currently 
#entering into the selected categorie. It puts a '1' in the excel file. I check what row that '1' is in using pandas to add that item 
#(the price of the item anyway), into the categorie the 1 is under. This process is rather complicated for me to get right, thanks
#google.
class Enter_Info:
    def __init__(self):
        self.wb = openpyxl.load_workbook(filename)
        self.page = self.wb.active
        self.B1 = tk.Button(screen, text='Enter Information', command=m.clear).place(x=20, y=131)
        self.B2 = tk.Button(screen, text='Total', command=t.main_total).place(x=20, y=171)
        self.B3 = tk.Button(screen, text='Clear', command=m.clear).place(x=20, y=91)
        self.C1 = tk.Checkbutton(screen, text='GAS', variable=var.check1, font=('arial', 12)).place(x=400, y=86)
        self.C2 = tk.Checkbutton(screen, text='FOOD', variable=var.check2, font=('arial', 12)).place(x=400, y=106)
        self.C3 = tk.Checkbutton(screen, text='CLOTHES', variable=var.check3, font=('arial', 12)).place(x=400, y=126)
        self.C4 = tk.Checkbutton(screen, text='SUPPLIES', variable=var.check4, font=('arial', 12)).place(x=400, y=146)
        self.C5 = tk.Checkbutton(screen, text='LUXURY', variable=var.check5, font=('arial', 12)).place(x=400, y=166)
        self.C6 = tk.Checkbutton(screen, text='WITH_CREDIT', variable=var.check6, font=('arial', 12)).place(x=400, y=186)

    def enter(self):
        inf = [var.entry1.get(), var.entry2.get(), var.entry3.get(), var.entry4.get(), var.entry5.get(), var.entry6.get(),
        var.check1.get(), var.check2.get(), var.check3.get(), var.check4.get(), var.check5.get(), var.check6.get()]
        sheets = self.wb.sheetnames
        ws = self.wb[sheets[-1]]
        ws.append(inf)
        self.wb.save(filename)


info = Enter_Info()


screen.config(menu=m.M1)
screen.mainloop()
